version: '2'

services:
  tree-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: projektmanagement-frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    networks:
      - tree-network

networks:
  tree-network: